### ISSUE TITLE
[question] async_ and cpu bound code

### ISSUE THREAD

**Issue by lewoudar** [miguelgrinberg/greenletio#9]
Hi,
I think I have the answer but just to be sure, is it a bad idea to run cpu intensive code with `async` instead of running it in a threadpool? (my assumption is *yes* for the answer)

**Comment by miguelgrinberg** [comment]
Yeah, that's not going to work. It would be the same as running CPU heaving work in a proper `async` function. There is really no magic behind the `async_` decorator, it really makes your function behave like a real async function, with the same benefits and disadvantages.

**Comment by lewoudar** [comment]
Ok, thanks for the answer. Another question not related to the first one.
When writing code like this
```python
with patch_blocking():
    import requests
```
Will it just patch the concerned modules (ssl, socket, etc..) for the requests use? or will it patch the modules for everything else until the end of the program execution?

**Comment by miguelgrinberg** [comment]
The modules are patched while the code inside the with block runs. As soon as that ends, everything is restored to normal.

**Comment by lewoudar** [comment]
Many thanks for the clarification!

**Comment by spumer** [comment]
@miguelgrinberg 
Can you explain the idea behind this approach? I mean why you implement context manager instead regular function to patch? As you said same import will be ignored.

**Comment by miguelgrinberg** [comment]
@spumer this provides more control, and also is a bit more explicit. But if you want to use a monkey patching function you can write one yourself. Something like this:

```python
def monkey_patch_socket():
    with patch_blocking():
        import socket
```
